development:
  adapter: postgresql
  encoding: unicode
  database: samaritan_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: samaritan_test
  pool: 5
  timeout: 5000
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: samaritan_production
  pool: 5
  timeout: 5000
  username: postgres
  password: 
