development:
  adapter: postgresql
  encoding: unicode
  database: samaritan_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: samaritan_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: samaritan_production
  pool: 5
  timeout: 5000
